<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Ashwin Nanjappa">
  <title>Code Yarns – AttributeError with Python Enum</title>
  <style type="text/css">code{white-space: pre;}</style>
  <link rel="stylesheet" href="../styles.css">
  <!-- RSS feed -->
  <link rel="alternate" type="application/rss+xml" href="https://codeyarns.com/tech/rss.xml" />
  <!-- Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143311697-1">
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-143311697-1');
  </script>
  <!-- Google Adsense -->
  <script data-ad-client="ca-pub-1956250892185343" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
  </script>
  <!-- Twitter button -->
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</head>

<body>

<div class="contentbox">
<div class="header">
    <a href=".." class="header">Code Yarns ‍👨‍💻</a>
  </div>
  <div class="header">
    <a class="header2" href="https://codeyarns.com/tech/">Tech Blog</a> ❖ <a class="header2" href="https://codeyarns.com/personal/">Personal Blog</a>
  </div>
  <div class="header" style="padding-top: 10px;">
    <iframe src="https://duckduckgo.com/search.html?site=codeyarns.com&kp=-2&kc=1&prefill=Search this website" style="width:300px;height:40px;" frameborder="0"></iframe>
</div>
</div>

<br />

<div class="contentbox">
<header>
<h1 class="title">AttributeError with Python Enum</h1>
<p class="date">📅 2015-Jul-16 ⬩ ✍️ Ashwin Nanjappa ⬩ 🏷️ <a href='index.html#enum'>enum</a>, <a href='index.html#error'>error</a>, <a href='index.html#python'>python</a> ⬩ 📚 <a href="index.html">Archive</a></p>
</header>
<h2 id="problem">Problem</h2>
<p>I had code that had worked correctly with Python 2.7 and that used the old <a href="https://pypi.python.org/pypi/enum/"><strong>enum</strong></a> module. Recently it started throwing this error:</p>
<pre><code>$ ./foo.py 
Traceback (most recent call last):
  File &quot;./foo.py&quot;, line 146, in &lt;module&gt;
    main()
  File &quot;./foo.py&quot;, line 100, in draw_plot
    if PlotType.Line == plot_type:
  File &quot;/usr/local/lib/python2.7/dist-packages/enum/__init__.py&quot;, line 373, in __getattr__
    raise AttributeError(name)
AttributeError: Line</code></pre>
<h2 id="solution">Solution</h2>
<p>This error is caused when the <a href="https://pypi.python.org/pypi/enum34/"><strong>enum34</strong></a> module has been installed alongside the old enum module. enum34 is the backport for Python 2.x of the standard enum in Python 3.4. Many packages have started to use it and so it will be installed implicitly while installing another package. enum34 overrides the old enum files and causes this error.</p>
<p>You could remove enum34 and get rid of this error. But since Python 3.x has already adapted a new enum type, it might be wiser to uninstall the old enum and rewrite your code to use enum34. Its syntax is shown in <a href="2013/05/01/how-to-use-enum-in-python/">this example</a>.</p>
<p><strong>Tried with:</strong> Python 2.7.6 and Ubuntu 14.04</p>
</div>

<br />

<div class="contentbox">

<div class="footer"><a href="mailto:codeyarns@gmail.com" style="text-decoration: none; font-size: xx-large;">📧</a> <a href="https://twitter.com/codeyarns" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @codeyarns</a> <a href="https://www.buymeacoffee.com/codeyarns"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" style="height: 38px !important;width: 163px !important;" ></a></div>
</div>

</body>
</html>
