<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Ashwin Nanjappa" />
  <title>Docker no pull access error</title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<div id="header">
<h1 class="title">Docker no pull access error</h1>
<h2 class="author">Ashwin Nanjappa</h2>
<h3 class="date">2017-10-12 14:53:24+00:00</h3>
</div>
<h1 id="problem">Problem</h1>
<p>A <strong>Docker</strong> pull command to Docker hub that worked fine for all users failed only for one user. When she tried to pull, it threw up this error:</p>
<pre><code>repository some_org/some_image not found: does not exist or no pull access
The push refers to a repository [docker.io/some_org/some_image]</code></pre>
<p>Docker hub authentication and other details seemed to be in order.</p>
<h1 id="solution">Solution</h1>
<p>Turns out this user had run some docker commands before adding the Docker hub authentication. Those early commands had created a <code>~/.docker</code> directory. Details from this were conflicting with Docker hub authentication that was introduced later. Removing this directory fixed the issue.</p>
<p><strong>Tried with:</strong> Docker 1.11 and Ubuntu 14.04</p>
</body>
</html>
