<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Ashwin Nanjappa">
  <title>Code Yarns â€“ Docker no pull access error</title>
  <style type="text/css">code{white-space: pre;}</style>
  <link rel="stylesheet" href="../styles.css">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143311697-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-143311697-1');
  </script>
</head>
<body>
<a href="..">Code Yarns</a> / <a href="index.html">Tech Blog</a> / Search my site <script async src="https://cse.google.com/cse.js?cx=003521915278168649297:cryrlg7hahe"></script>
<div class="gcse-search"></div>
<hr />
<header>
<h1 class="title">Docker no pull access error</h1>
<p class="date">2017-10-12 14:53:24+00:00</p>
</header>
<h2 id="problem">Problem</h2>
<p>A <strong>Docker</strong> pull command to Docker hub that worked fine for all users failed only for one user. When she tried to pull, it threw up this error:</p>
<pre><code>repository some_org/some_image not found: does not exist or no pull access
The push refers to a repository [docker.io/some_org/some_image]</code></pre>
<p>Docker hub authentication and other details seemed to be in order.</p>
<h2 id="solution">Solution</h2>
<p>Turns out this user had run some docker commands before adding the Docker hub authentication. Those early commands had created a <code>~/.docker</code> directory. Details from this were conflicting with Docker hub authentication that was introduced later. Removing this directory fixed the issue.</p>
<p><strong>Tried with:</strong> Docker 1.11 and Ubuntu 14.04</p>
<hr />
<p><a href="rss.xml">RSS</a> - <a href="mailto:codeyarns@gmail.com">Contact</a></p>
</body>
</html>
